default: true
MD013:
  line_length: 120
  code_blocks: false
  tables: false
  headings: false
MD033: 
  allowed_elements: ["br", "sub", "sup", "img", "details", "summary"]
MD041: false
MD034: false  # Bare URLs allowed