repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [python]
      - id: detect-secrets
        name: detect-secrets
        entry: detect-secrets-hook
        language: system
