extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  comments:
    min-spaces-from-content: 2
    
  comments-indentation: false
  
  document-start: 
    present: false
    
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

ignore: |
  .github/workflows/
  monitoring/
  benchmarks/