agents:
  coder:
    model: "gpt-4"
    temperature: 0.1
    focus_areas:
      - "implementation details" 
      - "bug detection"
      - "performance optimization"
      - "edge cases"
  
  reviewer:
    model: "gpt-4"
    temperature: 0.2
    focus_areas:
      - "code quality"
      - "security vulnerabilities"
      - "maintainability"
      - "best practices"

# Response templates for agent conversation generation
response_templates:
  templates:
    coder:
      improvement_focused:
        - "Looking at the code implementation, I notice potential improvements in {focus_area}"
        - "From a technical standpoint, we could enhance the {focus_area} aspects"
        - "The implementation could benefit from better {focus_area} handling"
        - "I see opportunities to optimize the {focus_area} in this code"
      assessment:
        - "From a coding perspective, this {assessment_result}"
        - "The technical implementation {assessment_result}"
        - "Code-wise, this approach {assessment_result}"
        - "From a developer's viewpoint, this {assessment_result}"
      agreement:
        - "I {agreement_level} with the previous assessment regarding the implementation"
        - "I {agreement_level} about the technical approach discussed"
        - "From a coding perspective, I {agreement_level} with that analysis"
        - "I {agreement_level} with the implementation strategy mentioned"
    reviewer:
      concern_focused:
        - "From a review standpoint, I'm {concern_level} about the {focus_area} aspects"
        - "As a reviewer, I have {concern_level} regarding the {focus_area}"
        - "The code review perspective shows {concern_level} about {focus_area}"
        - "From a quality assurance angle, I'm {concern_level} about {focus_area}"
      findings:
        - "The code review indicates {finding_type}"
        - "My analysis reveals {finding_type}"
        - "The review process shows {finding_type}"
        - "Code examination suggests {finding_type}"
      opinion:
        - "I {opinion_type} about the current approach"
        - "I {opinion_type} regarding this implementation strategy"
        - "My review {opinion_type} about the proposed solution"
        - "From a reviewer's perspective, I {opinion_type} about this"
  
  substitution_options:
    focus_area:
      - "performance"
      - "error handling"
      - "edge cases"
      - "security"
      - "maintainability"
      - "readability"
      - "testing"
      - "scalability"
    assessment_result:
      - "looks solid"
      - "needs refactoring"
      - "has potential issues"
      - "shows good practices"
      - "could be improved"
      - "demonstrates clear logic"
    agreement_level:
      - "agree"
      - "disagree"
      - "partially agree"
      - "strongly agree"
      - "somewhat disagree"
    concern_level:
      - "concerned"
      - "satisfied"
      - "very concerned"
      - "moderately concerned"
      - "pleased"
      - "worried"
    finding_type:
      - "good practices"
      - "areas for improvement"
      - "security concerns"
      - "performance issues"
      - "code quality improvements"
      - "architectural considerations"
    opinion_type:
      - "concur"
      - "have reservations"
      - "strongly support"
      - "have mixed feelings"
      - "am optimistic"
      - "see potential issues"