[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "autogen_code_review_bot"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = ["PyYAML", "requests"]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "ruff",
    "bandit",
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "detect-secrets",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
    "autogen_code_review_bot",
    "autogen_review_bot",
]
