[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "autogen_code_review_bot"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
    "PyYAML>=6.0.0,<7.0.0",
    "requests>=2.31.0,<3.0.0"
]

[project.optional-dependencies]
monitoring = [
    "psutil>=5.9.0,<6.0.0"
]
dev = [
    "pre-commit>=3.5.0,<4.0.0",
    "ruff>=0.1.0,<1.0.0",
    "bandit>=1.7.0,<2.0.0",
    "pytest>=7.4.0,<9.0.0",
    "pytest-cov>=4.1.0,<6.0.0",
    "pytest-xdist>=3.3.0,<4.0.0",
    "detect-secrets>=1.4.0,<2.0.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
    "autogen_code_review_bot",
    "autogen_review_bot",
]
