name: Feature Request
description: Suggest an idea for AutoGen Code Review Bot
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - danieleschmidt

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What area does this feature affect?
      options:
        - Agent behavior and prompts
        - GitHub integration
        - Code analysis and linting
        - Performance and caching
        - Security and authentication
        - Documentation and usability
        - Deployment and operations
        - Testing and quality assurance
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (blocking current work)
        - High (would significantly improve workflow)
        - Medium (nice to have improvement)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/danieleschmidt/autogen-code-review-bot/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true