name: Autonomous Development Loop

on:
  schedule:
    # Run every 4 hours during business days
    - cron: '0 8,12,16,20 * * 1-5'
  workflow_dispatch:
    inputs:
      max_tasks:
        description: 'Maximum tasks to process'
        required: false
        default: '3'
        type: string

jobs:
  autonomous-development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/terragon/autonomous-iterative-dev'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -e .[dev]
        pre-commit install

    - name: Run autonomous development cycle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAX_TASKS: ${{ github.event.inputs.max_tasks || '3' }}
      run: |
        python scripts/autonomous_dev.py \
          --max-tasks=$MAX_TASKS \
          --backlog-file=BACKLOG.md \
          --create-pr

    - name: Update backlog and create PR
      if: success()
      run: |
        git config --local user.email "autonomous-dev@terragon-labs.com"
        git config --local user.name "Autonomous Development Bot"
        
        # Check if there are changes
        if ! git diff --quiet; then
          timestamp=$(date +"%Y%m%d-%H%M%S")
          branch_name="autonomous-dev/iteration-$timestamp"
          
          git checkout -b "$branch_name"
          git add .
          git commit -m "🤖 Autonomous development iteration

Generated with autonomous development loop
- Implemented highest priority tasks from backlog
- Updated documentation and tests
- Maintained code quality standards

🔗 Backlog: BACKLOG.md
📊 WSJF prioritization applied"
          
          git push origin "$branch_name"
          
          gh pr create \
            --title "🤖 Autonomous Development: $(date '+%Y-%m-%d %H:%M')" \
            --body "## Autonomous Development Iteration

This PR contains automated improvements based on the prioritized backlog.

### Changes Made
- Implemented top-priority tasks using WSJF methodology
- Applied TDD approach (tests first, then implementation)
- Updated documentation and maintained code quality

### Quality Assurance
- ✅ All tests passing
- ✅ Linting and security checks passed
- ✅ Pre-commit hooks validated
- ✅ Code coverage maintained/improved

### Next Steps
- Review and merge if quality standards met
- Backlog automatically re-prioritized for next iteration

---
🤖 Generated by Autonomous Development Loop" \
            --head "$branch_name" \
            --base main
        fi